'use strict';
const cases = window.ACCEPTANCE_CASES;
const $ = id => document.getElementById(id);
const storageKey = 'jingman-windows-acceptance-v1';
let records = {}, group = 'all';
try { const saved = JSON.parse(localStorage.getItem(storageKey) || '{}'); if(saved && typeof saved === 'object' && !Array.isArray(saved)) records=saved; } catch { $('saveState').textContent='浏览器不能读取历史记录；本轮可继续测试，请导出备份。'; }
const hash = new URLSearchParams(location.hash.slice(1));
const access = hash.get('access') || sessionStorage.getItem('jm-acceptance-key') || '';
if (hash.has('access')) { sessionStorage.setItem('jm-acceptance-key',access); history.replaceState(null,'',location.pathname); }
$('key').value=access;
$('project').textContent='工程文件夹：'+(window.ACCEPTANCE_PROJECT || '交付目录 / jingman-windows / miniprogram');
$('merchant').href='/#access='+encodeURIComponent(access);
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(access);$('saveState').textContent='口令已复制，粘贴到小程序连接页。';}catch{$('key').select();$('saveState').textContent='请按 Ctrl+C 复制选中的口令。';}};
fetch('/api/health').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{$('health').textContent=d.ok?'● 本机模拟服务运行中':'服务异常';}).catch(()=>{$('health').textContent='服务未连接，请运行 start.cmd';});
function statusOf(id) { return ['pass','fail','blocked'].includes(records[id]?.status)?records[id].status:'todo'; }
function save(){try{localStorage.setItem(storageKey,JSON.stringify(records));$('saveState').textContent='已保存到当前浏览器 · '+new Date().toLocaleTimeString();}catch{$('saveState').textContent='保存失败（可能存储空间不足），请立即导出记录。';$('saveState').classList.add('error');}}
function metrics(){const p=cases.filter(c=>statusOf(c.id)==='pass').length,f=cases.filter(c=>statusOf(c.id)==='fail').length,b=cases.filter(c=>statusOf(c.id)==='blocked').length; $('total').textContent=cases.length;$('pass').textContent=p;$('fail').textContent=f;$('left').textContent=cases.length-p-f-b;const percent=Math.round(100*(p+f+b)/cases.length);$('progress').value=percent;$('progressLabel').textContent=`已记录 ${percent}% · 暂无法测 ${b} 项`;}
function render(){const query=$('search').value.trim().toLowerCase(),filter=$('filter').value;const visible=cases.filter(c=>(group==='all'||group===c.group)&&(filter==='all'||statusOf(c.id)===filter)&&[c.title,c.steps,c.expected,c.id,c.platform].join(' ').toLowerCase().includes(query));$('cases').replaceChildren();$('sectionTitle').textContent=group==='all'?'全部验收项':group;$('empty').hidden=visible.length>0;
for(const c of visible){const tr=document.createElement('tr');tr.className=statusOf(c.id);const head=document.createElement('td');const id=document.createElement('span');id.className='case-id';id.textContent=c.id;const title=document.createElement('strong');title.textContent=c.title;const g=document.createElement('small');g.textContent=c.group;const platform=document.createElement('span');platform.className='platform';platform.textContent=c.platform;head.append(id,title,g,platform);tr.append(head);for(const text of [c.steps,c.expected]){const td=document.createElement('td');td.textContent=text;tr.append(td);}const result=document.createElement('td');const select=document.createElement('select');select.setAttribute('aria-label',c.id+' 验收结果');for(const [v,label] of [['todo','待测试'],['pass','通过'],['fail','未通过'],['blocked','暂无法测试']]){const o=new Option(label,v);select.add(o);}select.value=statusOf(c.id);const note=document.createElement('textarea');note.setAttribute('aria-label',c.id+' 问题备注');note.placeholder='角色、订单号、复现动作、截图文件名…';note.value=typeof records[c.id]?.note==='string'?records[c.id].note:'';select.onchange=()=>{records[c.id]={status:select.value,note:note.value,updatedAt:new Date().toISOString()};tr.className=select.value;save();metrics();if($('filter').value!=='all')render();};note.oninput=()=>{records[c.id]={status:select.value,note:note.value,updatedAt:new Date().toISOString()};save();};result.append(select,note);tr.append(result);$('cases').append(tr);}metrics();}
for(const name of ['all',...new Set(cases.map(c=>c.group))]){const button=document.createElement('button');button.textContent=name==='all'?'全部验收项':name;button.className=name==='all'?'active':'';button.onclick=()=>{group=name;for(const b of $('sections').children)b.classList.toggle('active',b===button);render();};$('sections').append(button);}
$('search').oninput=render;$('filter').onchange=render;
$('export').onclick=()=>{const data={version:'windows-acceptance-v1',baseCommit:'c87425f',exportedAt:new Date().toISOString(),scope:'开发者工具本机模拟验收；非真实支付/厂商接入/真机验收',cases:cases.map(c=>({...c,status:statusOf(c.id),note:records[c.id]?.note||'',updatedAt:records[c.id]?.updatedAt||null}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='京漫人工验收-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();
